## İnceleme

Önceki bölümlerde yalnızca işimize yaramayan dataları filtreledik. Bazı durumlarda ise emit edilen değerlere değil, sequence hakkında bilgiye ihtiyacımız olur. Şimdi bu işe yarayan metodları göreceğiz.

### all
 
 `all` metodu observable tarafından emit edilen değerlerin, belirtilen kriteri sağlaması durumunda `true` sağlamaması durumunda `false` döner. 
 
 ```java
public final Single<Boolean> all(Predicate<? super T> predicate) 
 ```
 
 ```java
 Observable<Integer> values = Observable.create(o -> {
            o.onNext(0);
            o.onNext(10);
            o.onNext(10);
            o.onNext(12);
            o.onComplete();
        });

values.all(i -> i % 2 == 0)
        .subscribe(
            v -> System.out.println(v),
            e -> System.out.println("Error: " + e));
 ```
 
 ```diff
 - Output
 
 true
 ```
 
Bu öperatör ile ilgili önemli noktalardan biri, seqeunce complete olana kadar ve ya bir errorla ya da koşulu sağlamayan bir değer ile karşılaşılana kadar boolean değerin emit edilmemesi. Çünkü `all` içinde belirtilen koşulu tüm seqeunce değerlerinin sağlaması gerekmetedir ve sequence sonlanmadan `true` değeri dönmez. Fakat koşulu sağlamayan bir değer ile karşılaşıldığında, sequencedeki diğer değerlere bakmaya gerek yoktur.

Yukarıdaki örnekten, `o.onComplete();` satırını silerek, konsola `true` basılmadığını görebilirsiniz.

Aşağıdaki örnekte koşulun sağlanmaması durumunu görebiliriz.

```java
  Observable<Long> values = Observable.interval(150, TimeUnit.MILLISECONDS).take(5);

Disposable disposable =
    values.all(i -> i < 3) // 0,1 ve 2'den sonra koşul sağlanmayacaktır
        .subscribe(
            v -> System.out.println("all = " + v),
            e -> System.out.println("all Error: " + e));

Disposable disposable1 =
    values.subscribe(
        v -> System.out.println(v),
        e -> System.out.println("Error: " + e),
        () -> System.out.println("Completed"));
```

```diff
- Output

0
1
2
all = false
3
4
Completed
```


Eğer observable'da bir error oluşursa, o ana kadar ki değerlerde sorun olmasa dahi, sequence bir errorla sonlanacaktır.

```java
Observable<Integer> values = Observable.create(o -> {
            o.onNext(0);
            o.onNext(2);
            o.onError(new Exception());
        });

Disposable disposable =
    values.all(i -> i < 3)
        .subscribe(
            v -> System.out.println(v),
            e -> System.out.println("Error: " + e));
```

```diff
- Output

Error: java.lang.Exception
```

Fakat o ana kadar ki değerlerden biri belirtilen koşulu sağlamazsa, sequence `false` emit edip sonlanacağından dolayı, `false` sağlayan değerden sonra error oluşsa bile bu error görülmeyecektir.


```java
Observable<Integer> values = Observable.create(o -> {
            o.onNext(0);
            o.onNext(1);
            o.onError(new Exception());
        });

Disposable disposable =
    values.all(i -> i % 2 == 0)
        .subscribe(
            v -> System.out.println(v),
            e -> System.out.println("Error: " + e));
```

```diff
- Output

false
```

Görüldüğü gibi `1`, `i % 2 == 0` koşulunu sağlamadı ve sequence sonlandı.

## exists



  

 
 